[package]
name = "auto-uploader"
version = "0.1.0"
edition = "2021"

[dependencies]
google-youtube3 = "6.0.0"
notify = "6.1.1"
serde = "1.0.213"
serde_json = "1.0.132"
thirtyfour = "0.34.0"
tokio = {version =  "1.41.0", features = ["full"]}
